---
- name: Test cron service fix
  hosts: local_nodes
  become: yes
  tasks:
    - name: Install cron package
      apt:
        name: cron
        state: present
        update_cache: yes

    - name: Start and enable cron service
      shell: |
        if command -v systemctl >/dev/null 2>&1; then
          systemctl start cron || systemctl start crond || true
          systemctl enable cron || systemctl enable crond || true
        else
          # For containers without systemd, start cron manually
          service cron start || /etc/init.d/cron start || cron || true
        fi
      failed_when: false

    - name: Verify cron daemon is running
      shell: pgrep -f cron || ps aux | grep -v grep | grep cron
      register: cron_running
      changed_when: false
      failed_when: false

    - name: Display cron status
      debug:
        msg: "Cron daemon status: {{ 'Running' if cron_running.rc == 0 else 'Not running' }}"